services:
  mysql-master:
    image: mysql:8.4
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: testdb
    volumes:
      - ./master/conf/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./master/init:/docker-entrypoint-initdb.d
    ports:
      - "3506:3306"
    networks:
      - mysql-replication

  mysql-slave:
    image: mysql:8.4
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
    volumes:
      - ./slave/conf/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ./slave/init:/docker-entrypoint-initdb.d
    ports:
      - "3507:3306"
    networks:
      - mysql-replication
    depends_on:
      - mysql-master

networks:
  mysql-replication:
    driver: bridge
