services:
  mysql-master:
    image: mysql:8.4
    container_name: mysql-master
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
    volumes:
      - ./master/conf/master.cnf:/etc/mysql/conf.d/master.cnf
      - ./master/init:/docker-entrypoint-initdb.d
    ports:
      - "3506:3306"
    networks:
      - mysql-replication
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s

  mysql-slave:
    image: mysql:8.4
    container_name: mysql-slave
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./slave/conf/slave.cnf:/etc/mysql/conf.d/slave.cnf
      - ./slave/init:/docker-entrypoint-initdb.d
    ports:
      - "3507:3306"
    networks:
      - mysql-replication
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "--silent"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    depends_on:
      mysql-master:
        condition: service_healthy

networks:
  mysql-replication:
    driver: bridge
